### ISSUE TITLE
mutli gpu training will hung

### ISSUE THREAD

**Issue by runzeer** [stepfun-ai/Step1X-3D#12]
The multi gpu training for the diffusion model will hung on the first gpu initialization according to the command

<img width="808" alt="Image" src="https://github.com/user-attachments/assets/ba523b18-1a90-4a1f-9fb0-bfb28b441a28" />

torchrun train.py --config configs/train-geometry-diffusion/step1x-3d-geometry-label-1300m.yaml  --train --gpu 0,1,2,3,4,5,6,7
It seems that it did not initialize

could you please help me ?

**Comment by runzeer** [comment]
I add the local-rank to the argparse and used the distributed.launch and it works. But when I used the deepspeed_strategy_3, it    hang again. Have you ever tried the deepspeed_strategy_3?

**Comment by LuoMayao** [comment]
I meet the same question，could you tell me how to deal with it with your strategy that was mentioned in your conment?——“I add the local-rank to the argparse and used the distributed.launch and it works. But when I used the deepspeed_strategy_3, it hang again. Have you ever tried the deepspeed_strategy_3?”

**Comment by LiuLiuJerry** [comment]
> The multi gpu training for the diffusion model will hung on the first gpu initialization according to the command
> 
> <img alt="Image" width="808" src="https://private-user-images.githubusercontent.com/14292495/444781590-ba523b18-1a90-4a1f-9fb0-bfb28b441a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ1NDYyNjUsIm5iZiI6MTc1NDU0NTk2NSwicGF0aCI6Ii8xNDI5MjQ5NS80NDQ3ODE1OTAtYmE1MjNiMTgtMWE5MC00YTFmLTlmYjAtYmZiMjhiNDQxYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA3VDA1NTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MTkwNTMwYzNkOWNlZjAwMjI2OWIzZmE0MTIxNjBmZmRhZWEzNzIyMGM0NjVlODk0Zjg1OTFiNTE5NjI4OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nfQmrOH25cSaGDrhaoYKstVIIqg0bXR5SFpfrQ8pXjk">
> torchrun train.py --config configs/train-geometry-diffusion/step1x-3d-geometry-label-1300m.yaml --train --gpu 0,1,2,3,4,5,6,7 It seems that it did not initialize
> 
> could you please help me ?

Hi，same problem here, what do you mean by 'add the local-rank to the argparse '?  where should I add this parameter to? 
Thanks

**Comment by LuoMayao** [comment]
I solve the problem with extra declaration of ‘--standalone’ to ensure all rank can run on single node.Here is my command：
torchrun --standalone --nproc_per_node=8 train.py --config "configs/train/config.yaml" --train --gpu 0,1,2,3,4,5,6,7
